name: Build a Docker image and Push it to ACR

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: azure/docker-login@v1
        with:
          login-server: pythonbot.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t pythonbot.azurecr.io/pythonbot:${{ github.sha }}
          docker push pythonbot.azurecr.io/pythonbot:${{ github.sha }}
